
POST http://localhost:80/players/ketil
###
POST http://localhost:80/players/Steinar
###
POST http://localhost:80/players/Anolan
###
POST http://localhost:80/players/Johan
###

GET http://localhost:80/players
###

POST http://localhost:80/startGame
###

GET http://localhost:80/game
###


POST http://localhost:80/game/bid/pass
###

POST http://localhost:80/game/bid/7clubs
###

POST http://localhost:80/game/bid/7diamonds
###

POST http://localhost:80/game/bid/7hearts
###

POST http://localhost:80/game/bid/7spades
###

POST http://localhost:80/game/bid/7notrump
###


POST http://localhost:80/game/bid/8clubs
###



POST http://localhost:80/restartGame
###